[package]
name = "tinyase"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { version = "2.0.17", default-features = false }
zerocopy = { version = "0.8.31", features = ["derive"] }
zerocopy-derive = "0.8.31"
